### PR TITLE
Change Gallery Columns functionality

### PR DESCRIPTION
**Pull request by Ismael034**
Hi,
I have changed the way the gallery columns setting is shown.

### CODE REVIEW

**Comment by leonlatsch** [comment]
@Ismael034 I see you show a dialog insted if this SwitchPreference.
This can be achieved by using ListPreference. I was unsure what to use but if we do it with a Dialog, we should use ListPreference

**Comment by Ismael034** [comment]
> SwitchPreference

I implemented a Dialog because it look better and you can easily add options like add the option for the user to introduce a custom value in the dialog. I think that the user cannot introduce a custom value with ListPreference

**Comment by leonlatsch** [comment]
@Ismael034 I am also not sure, if gallery columns will stay, because in landscape mode (currently disabled, but I want to use it again), there we have to use a other number of columns.
Also, I added 3,4,5 on purpose, I dont wanted the user to go crazy with this number.

**Comment by leonlatsch** [comment]
@Ismael034 I think, I will close this pr. Once im sure, how to handle columns in landscape mode, it will show if we even need this preference. But Thank you really much!

**Comment by Ismael034** [comment]
Ok, No problem.
If you need some help in any part of the  project, please, fell free to contact me

**Pull request closed without merging**
