### PR TITLE
App / Readme Translation to Dutch

### PR DESCRIPTION
**Pull request by timnea**
**Description:**

*describe your pr here*

**Tasks:**
- [ ] Build CI Runs
- [ ] Code Analysis up to standards

### CODE REVIEW

**Comment by leonlatsch** [comment]
Thanks for the controbution, but the README will stay english only.

Please revert the readme and Ibwill look at the Translation.

**Comment by timnea** [comment]
I only added a shortcut in the english readme file to another readme file.

**Comment by leonlatsch** [comment]
I know. But:

- The readme is also updated automatically by a pipeline
- Everything here in GitHub should be understood by everyone and therefore be in english.

The language for pr's, issues, the readme and everything else is english.

I am very thankful for the app translation, but I won't accept the pr in this form.

**Comment by timnea** [comment]
I made a new pull request with only the app translation #132

**Pull request closed without merging**
