### PR TITLE
Feature/#36 import videos

### PR DESCRIPTION
**Pull request by leonlatsch**
**Description:**

- Import Videos.
- New Import Menu

**Checklist:**
- [x] New Import Menu
- [x] Import Videos
- [x] Create video thumbnails
- [x] Add icon for videos in galery grid
- [x] Add Video Player
- [x] Adjust image viewer to show a preview of the video
- [x] Refactor ImageViewer to be a fragment too. Last step to single activity
- [x] Add share to Photok filter for videos
- [x] Implement buffered loading

### CODE REVIEW

**Comment by leonlatsch** [comment]
@aniquepligence I saw your fork. Does creating video thumbnails work with Glide 4? If so, we might use Glide for more than just that😃 .

**Comment by leonlatsch** [comment]
@IzzySoft do you know, if F-Droid will accept [ExoPlayer](https://exoplayer.dev/)?

**Comment by IzzySoft** [comment]
I think we have some apps using it, but I'm not entirely sure. As long as it doesn't have non-free dependencies it should be fine. Oh, wait: [this one](https://github.com/google/ExoPlayer)? In that case, remember for the build recipe:

```yaml
    srclib:
      - ExoPlayer@r2.13.2
```

(or whichever version you need). It's even already available as `srclib` at F-Droid :smiley: Just make sure to not drag in its `exoplayer-cast` plugin, that would be a show-stopper (proprietary).

**Comment by leonlatsch** [comment]
> Personal Note
Current Stage: Some videos are working:

```
VID_NOT_WORKING.mp4: ISO Media, MP4 v2 [ISO 14496-14]
VID_WORKING.mp4:          ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]
```

**Comment by leonlatsch** [comment]
TODO's before merge: 

- [ ] Fix player binding at rotation
- [ ] Finalize player ui

**Comment by JakobKamper** [comment]
- [ ] Fix crash when rotating Video thats already playing
- [ ] Fix loading older Backups (When loading a Backup that was created in a previous version, only the Thumbnails are visible, the actual pictures are blank and cant be exported)
- [ ] Fix crash trying to export videos

**Comment by comparesheriff** [comment]
>     Fix loading older Backups (When loading a Backup that was created in a previous version, only the Thumbnails are visible, the actual pictures are blank and cant be exported)

@JakobKamper -> The fixing of loading for older backups could be low priority imho, so its not a release stopper. When loading the backup, the version of the backup is checked against the current version. Depending on the complexity of this issue, I think it would be okay to give an incompatibility warning (and fix the issue in a later release). But then you should have a popup to alert the user to create new backups on update at least :sweat_smile: 

The other two fixes are very much needed though for this MR :smile: 

@leonlatsch what do you think?

**Comment by leonlatsch** [comment]
> >     Fix loading older Backups (When loading a Backup that was created in a previous version, only the Thumbnails are visible, the actual pictures are blank and cant be exported)
> 
> @JakobKamper -> The fixing of loading for older backups could be low priority imho, so its not a release stopper. When loading the backup, the version of the backup is checked against the current version. Depending on the complexity of this issue, I think it would be okay to give an incompatibility warning (and fix the issue in a later release). But then you should have a popup to alert the user to create new backups on update at least :sweat_smile: 
> 
> The other two fixes are very much needed though for this MR :smile: 
> 
> @leonlatsch what do you think?

@comparesheriff This feature changed the way backups work. I think it should be fixed.

I decided not to show the user any compatibility warnings and treat every backup diffrently depending on the version.

This way the user gets the best experiance out of the app.

Also: The original plan was to release videos alongside with collectiins but I may not donthis because so many people are waiting for video support.

**Pull request merged**
