### PR TITLE
Feature: Credits page

### PR DESCRIPTION
**Pull request by leonlatsch**
**Description:**

New credits page as described in #39 .

**Tasks:**
- [x] Build CI Runs
- [x] Code Analysis up to standards

### CODE REVIEW

**Comment by leonlatsch** [comment]
Sooo. I have implemented a basic Credits page. This will show your entry in CONTRIBUTORS.md <b>in the app.</b>
Since I respect your privacy, I want you to give you the opportunity to remove your entry before the next release.

So @Ismael034 @sr093906 @mezysinc @DRSchlaubi , if you don't want your entry (the one you created yourself in CONTRIBUTORS.md) in the app, you can just reply to this comment and I will remove it.

FYI:
The entries look loke this:

image
On click ot will open your website or github profile.

> You can see the new json file in this pr.

I would really like to keep all the contributors in this file, but I wanted to give you the opportunity.
Thank you.

**Comment by sr093906** [comment]
Please remove it.

**Comment by leonlatsch** [comment]
So this is finished. If you want your entry remove, just submit a pr.

**Comment by leonlatsch** [comment]
@sr093906 @Ismael034 @mezysinc Translation needed

**Pull request merged**
