### PR TITLE
Release/1.3.0

### PR DESCRIPTION
**Pull request by leonlatsch**
**Description:**

Release PR for Version 1.3.0

App should be fully tested before merge and release.

Please commit/merge everything missing into branch `release/1.3.0`!

Everything pushed to `develop` won't be used in this version!

Wanna help testing?

Download precompiled snapshot version:
[Photok-snapshot-1.3.0-0b802bd-UNSIGNED.zip](https://github.com/leonlatsch/Photok/files/6742320/Photok-snapshot-1.3.0-0b802bd-UNSIGNED.zip)

**Tasks:**
- [x] Build CI Runs
- [x] Code Analysis up to standards

### CODE REVIEW

**Comment by leonlatsch** [comment]
- [ ] Fix status bar in video player

**Comment by comparesheriff** [comment]
- [ ] Video Import has wrong Label on progress bar "Importing Photo(s)"
- [ ] Consider Renaming Different Labels to "files" instead of "photos" (e.g. on deletion or in the overview)

Also the progress bar updates only on percentage of completed files (e.g. 1 of 3 files = 33%), which can be confusing when importing a single large video (nothing happens for a while then it jumps from 0 to 100%).
Maybe its possible to display some kind of spinner or something like, so users can get feedback (and don't have to fear that the app froze), when importing large videos?

In general all operations using videos take quite some time (especially importing backups containing videos), but I guess this can't really be helped as videos are obviously quite a lot bigger than just images.

**Comment by leonlatsch** [comment]
> * [ ]  Video Import has wrong Label on progress bar "Importing Photo(s)"
> * [ ]  Consider Renaming Different Labels to "files" instead of "photos" (e.g. on deletion or in the overview)
> 
> Also the progress bar updates only on percentage of completed files (e.g. 1 of 3 files = 33%), which can be confusing when importing a single large video (nothing happens for a while then it jumps from 0 to 100%).
> Maybe its possible to display some kind of spinner or something like, so users can get feedback (and don't have to fear that the app froze), when importing large videos?
> 
> In general all operations using videos take quite some time (especially importing backups containing videos), but I guess this can't really be helped as videos are obviously quite a lot bigger than just images.

"Files" is a good idea. I will do that. For the loading its like you said. Videos just take longer ¯\_(ツ)_/¯

**Comment by leonlatsch** [comment]
I will just rename the german and english ones for now and create an issue for the translator to do the same for a later patch version.

**Pull request merged**
